import structlog
from typing import Dict, Any
from src.clients.confluence_client import ConfluenceClient
from src.services.workspace_service import WorkspaceService

logger = structlog.get_logger(__name__)

class DocumentHandler:
    """Handles document generation events and converts them to Confluence pages."""
    
    def __init__(self, workspace_service: WorkspaceService):
        self.workspace_service = workspace_service
        
    async def handle_document_event(self, event: Dict[str, Any]) -> None:
        """Process document generation events (e.g., requirement.prd.generated).
        
        Args:
            event: Kafka event payload
        """
        tenant_id = event.get("tenant_id") or event.get("workspace_id")
        if not tenant_id:
            logger.error("missing_tenant_id_in_event")
            return

        # Fetch dynamic config
        config = await self.workspace_service.get_confluence_config(tenant_id)
        if not config:
            logger.error("could_not_resolve_confluence_config", tenant_id=tenant_id)
            return

        # Initialize client with dynamic config
        confluence_client = ConfluenceClient(config)
        
        payload = event.get("payload", {})
        doc_data = payload.get("data") or payload.get("prd") or {}
        doc_type = event.get("event_type", "document").split(".")[-2].upper()
        conversation_id = payload.get("conversation_id", "Unknown")
        
        # Determine Title
        # Attempt to find a title in the data, or fallback to event type
        project_overview = doc_data.get("Project Overview", {})
        project_name = project_overview.get("Project Title") or doc_data.get("title") or "Untitled Document"
        version = project_overview.get("Version") or doc_data.get("version") or "v1.0"
        title = f"{doc_type}: {project_name} ({version}) - {conversation_id[:8]}"
        
        # Convert JSON to XHTML (Confluence Storage Format)
        xhtml_content = self._format_data_to_xhtml(doc_data, doc_type)
        
        try:
            logger.info("handling_document_event", title=title, doc_type=doc_type, conversation_id=conversation_id, tenant_id=tenant_id)
            await confluence_client.create_page(
                title=title,
                content_xhtml=xhtml_content
            )
            logger.info("confluence_page_handled_successfully", title=title)
        except Exception as e:
            logger.error("confluence_page_handling_failed", error=str(e), title=title)
            raise

    def _format_data_to_xhtml(self, data: Dict[str, Any], doc_type: str) -> str:
        """Convert document JSON data to Confluence Storage Format (XHTML)."""
        html = []
        
        # Add summary/metadata at top
        html.append(f"<h1>{doc_type}</h1>")
        html.append("<p><i>Automatically generated by AI Society Intelligence Service.</i></p>")
        
        for section, content in data.items():
            html.append(f"<h2>{section}</h2>")
            
            if isinstance(content, dict):
                html.append("<ul>")
                for key, value in content.items():
                    if isinstance(value, list):
                        html.append(f"<li><b>{key}:</b>")
                        html.append("<ul>")
                        for item in value:
                            html.append(f"<li>{item}</li>")
                        html.append("</ul></li>")
                    else:
                        html.append(f"<li><b>{key}:</b> {value}</li>")
                html.append("</ul>")
            elif isinstance(content, list):
                html.append("<ul>")
                for item in content:
                    html.append(f"<li>{item}</li>")
                html.append("</ul>")
            else:
                html.append(f"<p>{content}</p>")
                
        return "".join(html)
